NvEnc Limit Stop Testing for device -- Various Fixes
BotBlake/pyTAB pull request #28
Opened 2024-10-01 17:24 UTC by nathangur

Issue relating to this PR: https://github.com/BotBlake/pyTAB/issues/27

- Better Nvidia driver limit checks with a now persistent known limit of the GPU driver across tests.

- Fixed some weird cuda stuff

- Use ffprobe now for checking the files

- More comprehensive and in-depth ffmpeg error logging

- Fixed MaxStreams for Nvidia GPU's always being 1 after a test was finished

Possible issues:

On my machine the CPU likes to jump from 1 worker to 9 workers, no clue if it's just really excited to be benchmarking or if it's just bugged.

2024-10-01 20:23 UTC, BotBlake commented
Note: The high jump in workers is expected.
This is part of our "worker upscaling"  logic. 

For upscaling the amount of workers, we generaly take a look at the speed of the run.
So e.g. :

```
Run: 1, Workers: 1, Speed: 5.2x
-> Workers = Workers + Speed
Run: 2, Workers: 6, Speed: 1.3x
[...]
```

We also have downscaling measures that will compensate for too heavy upscaling.

I assume this is the reason that your GPU jumps from 1 workers straight to 9.
Same should also happen on GPU tests, if the GPU is powerfull enough.

That way we save loads of time compared to upscaling by 1 every run

2024-10-02 12:53 UTC, BotBlake commented
Note:
The Script will Scale Up the Worker amount, until some sort of failure happened.

In some specific conditions we Scale down to verify that we found the absolute Maximum of streams.

Adding a value to `failure_reason` implies that a failure has happened!

2024-10-02 14:58 UTC, BotBlake commented
Note:
The Script will Scale Up the Worker amount, until some sort of failure happened.

In some specific conditions we Scale down to verify that we found the absolute Maximum of streams.

Adding a value to `failure_reason` implies that a failure has happened!

2025-01-19 20:39 UTC, BotBlake requested changes
A lot of the issues have been resolved on the latest `develop`
However the implementation of an nvenc limit detection is still missing!

It would need to be moved into a standalone method that can be called ONCE before actual testing! Then all tests for that GPU could be skipped!

2025-01-19 20:39 UTC, BotBlake commented on pytab/core.py
> +        if is_nvidia_gpu:
I say its best to have a dedicated function to test a GPUs limit. This approach in general seems to be fine as well though!

2025-01-19 20:39 UTC, BotBlake commented on pytab/core.py
> +                gpu_worker_counts = [total_workers]
I would prefer to only run this nvenc limit test once instead of every run.

2025-01-19 20:39 UTC, BotBlake commented on pytab/core.py
> +            # Non-NVIDIA GPUs (HAVE NOT TESTED) or CPU
A lot of code is doubled here, lets try to only seperate nvidia from the rest, when its needed

2025-01-19 20:39 UTC, BotBlake commented on pytab/core.py
> +    if not failure_reason:
We should only fail runs when a failure has happened. 
A failure SHOULD also come with a valid failure reason.

It cant hurt to append one regardless, however there should ALWAYS be one anyways!

2025-01-19 20:39 UTC, BotBlake commented on pytab/core.py
> +            "single_worker_speed": runs[0]["speed"],
This changes the meaning of the returned data!
We want to know the values of the LAST run.
You provide data of the first run!

2025-01-19 20:39 UTC, BotBlake commented on pytab/core.py
> +        gpu_idx = 0  # The CUDA device index is 0
If this is the second CUDA device, then its id will not be 0.
However I do believe this was done to circumvent an issue that is fixed on the latest version of `develop`

2025-01-19 20:39 UTC, BotBlake commented on pytab/core.py
> +                            test_data["selected_cpu"] = -1
None is correct. The API wants us to return none. 
For more info check the [Whitepaper](https://github.com/JPVenson/Jellyfin.HardwareVisualizer/blob/main/HWA-Client-Whitepaper.md)

2025-01-19 20:39 UTC, BotBlake commented on pytab/worker.py
> +def run_ffmpeg(pid: int, ffmpeg_cmd: list, gpu_idx: int) -> tuple:
Theese fixes have been fixed on server side.
However this implementation should also not happen in worker.py

If the ffmpeg command is faulty, the entire run is faulty. 
If not the entire benchmark at best.

Therefore this logic would need to be in core.py

2025-01-19 20:39 UTC, BotBlake commented on pytab/worker.py
> +def parse_ffmpeg_error(stderr):
proper-ish ffmpeg parsing has been implemented on develop.
However its not capable to detect nvenc limits reliably!

2025-01-19 20:39 UTC, BotBlake commented on pytab/worker.py
> +                failure_reasons.append(f"Worker {pid} exception: {str(e)}")
I highly suggest not adding stack-traces to the results

2025-01-19 20:39 UTC, BotBlake commented on pytab/worker.py
> +        return True, failure_reasons
see reasoning in the core. We need to relete the raw data, since runs with failed Worker are not counted

2025-01-19 21:09 UTC, nathangur commented
I'll review the latest changes and reimplement that nvenc limit on the latest `develop` version. Might be a little bit though ;)

2025-01-19 21:20 UTC, BotBlake commented
Sweet!
If you have any questions as usual, feel free to hop onto the matrix/ discord room and ask me/ us.

Thank you for your efforts!
Also excuse the long review time.
We just fixed both the Server and Client and now has been a good time to reference the client and server code 😅

2025-02-01 16:12 UTC, BotBlake commented
@nathangur NvEnc detection is now available in develop.

2025-02-05 02:38 UTC, BotBlake commented
This should now be fully implemented in the latest version of debug, so I’ll go ahead and close this PR.

- NvEnc limit detection now runs once before starting the benchmark.
- During benchmarking, we only attempt {limit} workers when a limit has been detected.
- Verification and fixing of server commands is no longer necessary, as this was due to a now-fixed server-side issue.

Additionally, we're working on implementing a logger, so FFmpeg logging will see improvements soon as well!

Thank you for your time and contribution - it’s much appreciated! I’d be happy to see your input on future improvements or any other areas you’re interested in contributing to.

Kind regards

2025-02-05 02:38 UTC, closed without merging